export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
      ],
    ],
    'scope-enum': [
      1, // Warning level — allows new scopes
      'always',
      [
        'button',
        'input',
        'modal',
        'tabs',
        'dropdown',
        'select',
        'toast',
        'tooltip',
        'table',
        'card',
        'badge',
        'avatar',
        'checkbox',
        'radio',
        'switch',
        'spinner',
        'typography',
        'tokens',
        'theme',
        'layout',
        'icons',
        'hooks',
        'utils',
        'config',
        'deps',
        'ci',
      ],
    ],
    'header-max-length': [2, 'always', 100],
  },
};
