// This file is auto-generated by scripts/generate-docs-data.mjs
// Do not edit this file manually.

export const componentVersions = {
  "accordion": [
    "1.0.0"
  ],
  "alert": [
    "1.0.0"
  ],
  "alert-dialog": [
    "1.0.0"
  ],
  "aspect-ratio": [
    "1.0.0"
  ],
  "avatar": [
    "1.0.0"
  ],
  "badge": [
    "1.0.0"
  ],
  "big-calendar": [
    "1.0.0"
  ],
  "breadcrumb": [
    "1.0.0"
  ],
  "button": [
    "1.0.0"
  ],
  "button-group": [
    "1.0.0"
  ],
  "calendar": [
    "1.0.0"
  ],
  "card": [
    "1.0.0"
  ],
  "carousel": [
    "1.0.0"
  ],
  "chart": [
    "1.0.0"
  ],
  "checkbox": [
    "1.0.0"
  ],
  "collapsible": [
    "1.0.0"
  ],
  "command": [
    "1.0.0"
  ],
  "context-menu": [
    "1.0.0"
  ],
  "dialog": [
    "1.0.0"
  ],
  "drawer": [
    "1.0.0"
  ],
  "dropdown-menu": [
    "1.0.0"
  ],
  "empty": [
    "1.0.0"
  ],
  "field": [
    "1.0.0"
  ],
  "form": [
    "1.0.0"
  ],
  "hover-card": [
    "1.0.0"
  ],
  "input": [
    "1.0.0"
  ],
  "input-group": [
    "1.0.0"
  ],
  "input-otp": [
    "1.0.0"
  ],
  "item": [
    "1.0.0"
  ],
  "kbd": [
    "1.0.0"
  ],
  "label": [
    "1.0.0"
  ],
  "menubar": [
    "1.0.0"
  ],
  "navigation-menu": [
    "1.0.0"
  ],
  "pagination": [
    "1.0.0"
  ],
  "popover": [
    "1.0.0"
  ],
  "progress": [
    "1.0.0"
  ],
  "radio-group": [
    "1.0.0"
  ],
  "resizable": [
    "1.0.0"
  ],
  "scroll-area": [
    "1.0.0"
  ],
  "select": [
    "1.0.0"
  ],
  "separator": [
    "1.0.0"
  ],
  "sheet": [
    "1.0.0"
  ],
  "sidebar": [
    "1.0.0"
  ],
  "skeleton": [
    "1.0.0"
  ],
  "slider": [
    "1.0.0"
  ],
  "sonner": [
    "1.0.0"
  ],
  "spinner": [
    "1.0.0"
  ],
  "switch": [
    "1.0.0"
  ],
  "table": [
    "1.0.0"
  ],
  "tabs": [
    "1.0.0"
  ],
  "textarea": [
    "1.0.0"
  ],
  "toast": [
    "1.0.0"
  ],
  "toggle": [
    "1.0.0"
  ],
  "toggle-group": [
    "1.0.0"
  ],
  "tooltip": [
    "1.0.0"
  ]
} as const;

export const novaExtrasVersions = {
  "animated-button": [
    "1.0.0",
    "1.1.0",
    "2.0.0-beta"
  ],
  "floating-input": [
    "1.0.0",
    "1.1.0",
    "2.0.0-beta"
  ],
  "glass-card": [
    "1.0.0",
    "1.1.0",
    "2.0.0-beta"
  ],
  "motion-dialog": [
    "1.0.0",
    "1.1.0",
    "2.0.0-beta"
  ],
  "shimmer-badge": [
    "1.0.0",
    "1.1.0",
    "2.0.0-beta"
  ]
} as const;
